<?php

namespace App\Exports;

use App\Models\PurchaseOrder;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Font;

class PurchaseOrderExport
{
    public function __construct(protected PurchaseOrder $purchaseOrder)
    {
    }

    public function generate(): string
    {
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $hidePrice = $this->purchaseOrder->hide_price ?? false;
        $lastCol = $hidePrice ? 'D' : 'F';
        $lastColLetter = $lastCol;

        // ── Document Properties ──
        $spreadsheet->getProperties()
            ->setTitle('Purchase Order ' . $this->purchaseOrder->po_number)
            ->setSubject($this->purchaseOrder->po_number)
            ->setDescription('Purchase Order document generated by the system')
            ->setCreator(config('app.name'));

        // ── Title Row ──
        $sheet->mergeCells('A1:' . $lastColLetter . '1');
        $sheet->setCellValue('A1', 'PURCHASE ORDER');
        $sheet->getStyle('A1')->applyFromArray([
            'font' => ['bold' => true, 'size' => 16, 'name' => 'Calibri', 'color' => ['argb' => 'FF1F4E79']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFD6E4F0']],
        ]);
        $sheet->getRowDimension(1)->setRowHeight(30);

        // ── PO Number Subtitle ──
        $sheet->mergeCells('A2:' . $lastColLetter . '2');
        $sheet->setCellValue('A2', $this->purchaseOrder->po_number);
        $sheet->getStyle('A2')->applyFromArray([
            'font' => ['size' => 12, 'name' => 'Calibri', 'italic' => true, 'color' => ['argb' => 'FF555555']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        ]);
        $sheet->getRowDimension(2)->setRowHeight(22);

        // ── Info Section ──
        $infoData = [
            ['PO Number:', $this->purchaseOrder->po_number, 'Status:', $this->purchaseOrder->status],
            ['Supplier:', $this->purchaseOrder->supplier?->name ?? 'N/A', 'Prepared By:', $this->purchaseOrder->preparedBy?->name ?? 'N/A'],
            ['Date Prepared:', $this->purchaseOrder->date_prepared->format('F d, Y'), 'Delivery Deadline:', $this->purchaseOrder->delivery_deadline?->format('F d, Y') ?? 'N/A'],
        ];

        if ($this->purchaseOrder->supplier?->address) {
            $infoData[] = ['Supplier Address:', $this->purchaseOrder->supplier->address, '', ''];
        }

        $infoStart = 4;
        $sheet->mergeCells('A' . $infoStart . ':' . $lastColLetter . $infoStart);
        $sheet->setCellValue('A' . $infoStart, 'DETAILS');
        $sheet->getStyle('A' . $infoStart)->applyFromArray([
            'font' => ['bold' => true, 'size' => 10, 'name' => 'Calibri', 'color' => ['argb' => 'FF1F4E79']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFE8E8E8']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT],
        ]);

        foreach ($infoData as $i => $rowData) {
            $r = $infoStart + 1 + $i;
            $sheet->setCellValue('A' . $r, $rowData[0]);
            $sheet->setCellValue('B' . $r, $rowData[1]);
            if (!empty($rowData[2])) {
                $sheet->setCellValue('C' . $r, $rowData[2]);
                $sheet->setCellValue('D' . $r, $rowData[3]);
            }
            $sheet->getStyle('A' . $r)->applyFromArray([
                'font' => ['bold' => true, 'size' => 10, 'name' => 'Calibri'],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT],
            ]);
            $sheet->getStyle('B' . $r)->applyFromArray([
                'font' => ['size' => 10, 'name' => 'Calibri', 'color' => ['argb' => 'FF333333']],
            ]);
            if (!empty($rowData[2])) {
                $sheet->getStyle('C' . $r)->applyFromArray([
                    'font' => ['bold' => true, 'size' => 10, 'name' => 'Calibri'],
                    'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT],
                ]);
                $sheet->getStyle('D' . $r)->applyFromArray([
                    'font' => ['size' => 10, 'name' => 'Calibri', 'color' => ['argb' => 'FF333333']],
                ]);
            }
        }

        // ── Items Section Header ──
        $itemsHeaderRow = $infoStart + 1 + count($infoData) + 1;
        $sheet->mergeCells('A' . $itemsHeaderRow . ':' . $lastColLetter . $itemsHeaderRow);
        $sheet->setCellValue('A' . $itemsHeaderRow, 'ITEMS');
        $sheet->getStyle('A' . $itemsHeaderRow)->applyFromArray([
            'font' => ['bold' => true, 'size' => 10, 'name' => 'Calibri', 'color' => ['argb' => 'FF1F4E79']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFE8E8E8']],
        ]);

        // ── Table Headers ──
        $row = $itemsHeaderRow + 1;
        $headers = $hidePrice ? ['#', 'Description', 'Unit', 'Qty'] : ['#', 'Description', 'Unit', 'Qty', 'Unit Price', 'Total'];

        $colLetters = $hidePrice ? ['A', 'B', 'C', 'D'] : ['A', 'B', 'C', 'D', 'E', 'F'];
        foreach ($headers as $i => $header) {
            $col = $colLetters[$i];
            $sheet->setCellValue($col . $row, $header);
        }

        $headerStyle = $sheet->getStyle('A' . $row . ':' . $lastColLetter . $row);
        $headerStyle->applyFromArray([
            'font' => ['bold' => true, 'size' => 10, 'name' => 'Calibri', 'color' => ['argb' => 'FFFFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF1F4E79']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'borders' => [
                'allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['argb' => 'FF1F4E79']],
            ],
        ]);
        $sheet->getRowDimension($row)->setRowHeight(20);

        // ── Items ──
        $items = $this->purchaseOrder->items;
        $dataStartRow = $row + 1;
        foreach ($items as $index => $item) {
            $row++;
            $sheet->setCellValue('A' . $row, $index + 1);
            $sheet->setCellValue('B' . $row, $item->item_description);
            $sheet->setCellValue('C' . $row, $item->unit);
            $sheet->setCellValue('D' . $row, $item->quantity);
            if (!$hidePrice) {
                $sheet->setCellValue('E' . $row, $item->unit_price ?? 0);
                $sheet->setCellValue('F' . $row, $item->total_price ?? 0);
            }

            // Alternating row colors
            $rowColor = ($index % 2 === 0) ? 'FFFFFFFF' : 'FFF2F7FB';
            $range = 'A' . $row . ':' . $lastColLetter . $row;
            $sheet->getStyle($range)->applyFromArray([
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => $rowColor]],
                'borders' => [
                    'allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['argb' => 'FFCCCCCC']],
                ],
            ]);

            // Center align # column
            $sheet->getStyle('A' . $row)->applyFromArray([
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            ]);
            // Left align description
            $sheet->getStyle('B' . $row)->applyFromArray([
                'font' => ['size' => 10, 'name' => 'Calibri'],
                'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
            ]);
            // Center align unit
            $sheet->getStyle('C' . $row)->applyFromArray([
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            ]);
            // Right align qty
            $sheet->getStyle('D' . $row)->applyFromArray([
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT, 'vertical' => Alignment::VERTICAL_CENTER],
            ]);
            $sheet->getRowDimension($row)->setRowHeight(18);
        }

        $dataEndRow = $row;

        if (!$hidePrice) {
            // ── Total Row ──
            $row++;
            $sheet->mergeCells('A' . $row . ':E' . $row);
            $sheet->setCellValue('A' . $row, 'TOTAL AMOUNT');
            $sheet->setCellValue('F' . $row, $this->purchaseOrder->total_amount ?? 0);
            $sheet->getStyle('A' . $row . ':F' . $row)->applyFromArray([
                'font' => ['bold' => true, 'size' => 11, 'name' => 'Calibri', 'color' => ['argb' => 'FF1F4E79']],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFD6E4F0']],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT, 'vertical' => Alignment::VERTICAL_CENTER],
                'borders' => [
                    'allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['argb' => 'FF1F4E79']],
                ],
            ]);
            $sheet->getStyle('F' . $row)->getNumberFormat()->setFormatCode('₱ #,##0.00');
            $sheet->getRowDimension($row)->setRowHeight(22);

            // ── Currency Format ──
            $priceRange = 'E' . $dataStartRow . ':F' . $dataEndRow;
            $sheet->getStyle($priceRange)->getNumberFormat()->setFormatCode('₱ #,##0.00');
        }

        // ── Notes ──
        if ($this->purchaseOrder->notes) {
            $row += 2;
            $sheet->mergeCells('A' . $row . ':' . $lastColLetter . $row);
            $sheet->setCellValue('A' . $row, 'NOTES');
            $sheet->getStyle('A' . $row)->applyFromArray([
                'font' => ['bold' => true, 'size' => 10, 'name' => 'Calibri', 'color' => ['argb' => 'FF1F4E79']],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFE8E8E8']],
            ]);
            $row++;
            $sheet->mergeCells('A' . $row . ':' . $lastColLetter . $row);
            $sheet->setCellValue('A' . $row, $this->purchaseOrder->notes);
            $sheet->getStyle('A' . $row)->applyFromArray([
                'font' => ['size' => 10, 'name' => 'Calibri', 'italic' => true, 'color' => ['argb' => 'FF555555']],
            ]);
        }

        // ── Footer ──
        $row += 2;
        $sheet->mergeCells('A' . $row . ':' . $lastColLetter . $row);
        $sheet->setCellValue('A' . $row, 'Generated on ' . now()->format('F d, Y h:i A') . ' | ' . $this->purchaseOrder->po_number);
        $sheet->getStyle('A' . $row)->applyFromArray([
            'font' => ['size' => 9, 'name' => 'Calibri', 'italic' => true, 'color' => ['argb' => 'FF999999']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        ]);

        // ── Auto-size columns ──
        $columns = $hidePrice ? range('A', 'D') : range('A', 'F');
        foreach ($columns as $column) {
            $sheet->getColumnDimension($column)->setAutoSize(true);
        }

        // ── Print Settings ──
        $sheet->getPageSetup()->setOrientation(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::ORIENTATION_LANDSCAPE);
        $sheet->getPageSetup()->setPaperSize(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::PAPERSIZE_A4);
        $sheet->getPageMargins()->setTop(0.5);
        $sheet->getPageMargins()->setBottom(0.5);

        // ── Write to output buffer ──
        $writer = new Xlsx($spreadsheet);
        ob_start();
        $writer->save('php://output');
        $excelOutput = ob_get_contents();
        ob_end_clean();

        return $excelOutput;
    }

    public function fileName(): string
    {
        return 'purchase-order-' . str_replace('/', '-', $this->purchaseOrder->po_number) . '.xlsx';
    }
}